import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | NAZI SHARIFI",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="h-20 w-full bg-cyan-900 space-x-12 text-white text-2xl flex justify-center items-center ">
          <a href="about">About</a>
          <a href="about">product</a>
          <a href="about">Login</a>
          <a href="about">Signup</a>
        </nav>
        {children}
        <footer className="h-20 w-full bg-gray-800 text-white text-center flex justify-center items-center text-4xl">Footer</footer>
      </body>
    </html>
  );
}
